name: Daily Telegram Message

on:
  schedule:
    - cron: '0 7 * * *'  # 7 AM UTC = 8 AM Nigeria
  workflow_dispatch:

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests schedule

      - name: Run Telegram Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SCHEDULE_TIME: "08:00"
          SEND_ON_START: "true"
        run: python New_Age_FxCBot.py
